rvm: 
  - 1.9.3
notifications:
  email:
    - 'houdini+travis@clanspum.net'
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.5.1
